# Use the official ActiveMQ image as the base image
FROM symptoma/activemq:5.18.3

# Copy the custom activemq.xml file to the ActiveMQ configuration directory
COPY activemq.xml /opt/activemq/conf/activemq.xml
