version: '3'

services:
  # The load balancer
  nginx:
    image: nginx:stable-alpine-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../front/dist:/usr/share/nginx/html:ro
    ports:
      - "8085:8085"
